### ISSUE TITLE
Warning: Stochastic program could not be solved, returned status: INFEASIBLE_OR_UNBOUNDED

### ISSUE THREAD

**Issue by maramos874** [martinbiel/StochasticPrograms.jl#16]
Hi, 
My stochastic model converges easily to the optimal solution when using the deterministic equivalent formulation. Nevertheless, PH and L-Shaped methods do not converge at all (see title). I have explored changing both algorithms options without success. Is there something I can explore further to find the source of non-convergence?

Kind regards

**Comment by martinbiel** [comment]
It is hard to say without knowing what model you are solving. Gurobi has some good [guidelines](https://www.gurobi.com/documentation/9.0/refman/num_grb_guidelines_for_num.html) for avoiding common numerical issues. The Gurobi parameter `BarHomogeneous` can be useful as well. For L-shaped you could consider the somewhat hidden `cut_scaling` parameter if generated cuts are ill-conditioned. There could be some issue as well because you say that the deterministic equivalent solves fine, but I cannot check that without access to the model.

**Comment by maramos874** [comment]
Thanks for the info, scaling the model coefficients surely has an impact on convergence, mostly for PH. I'm still having a hard time driving Benders decomposition towards convergence. is ```cut_scaling``` a StochasticPrograms parameter? How do you change it?

**Comment by martinbiel** [comment]
It should be either
```
MOI.set(sp, MOI.RawParameter("cut_scaling"), value)
```
or
```
set_optimizer_attributes(sp, cut_scaling = value)
```
It is mentioned in the `?LShapedAlgorithm` documentation, and any new general L-shaped parameter would be set in the same way. The parameter re-scales the lhs and rhs of all cuts by the provided value.
