### ISSUE TITLE
All the first-stage decision must be binary in the integer strategies

### ISSUE THREAD

**Issue by enri07** [martinbiel/StochasticPrograms.jl#33]
Hi,

I'm trying to solve an integer problem by using one of the Integer strategies proposed in the manual. I've tried both CombinatorialCuts and Convexification, but when I run the optimization the following error appears:

```
ERROR: LoadError: Combinatorial cuts require all first-stage decisions to be binary.
```

I was wondering if there is a solution to avoid this request. Thank you for your time.

**Comment by martinbiel** [comment]
I am afraid that this is a theoretical requirement for this strategy to converge. The convexification strategy configured with Gomory cutting planes is your only option for mixed-integer problems as of now. There is however no theoretical convergence guarantee using this method either since that would require special techniques not yet implemented.
