### ISSUE TITLE
How to access the optimal values of the second stage variables

### ISSUE THREAD

**Issue by Lessvn** [martinbiel/StochasticPrograms.jl#37]
Hello, I am trying to run the farmer.jl example. The model works find and the optimal solution is found. However when I enter ```JuMP.value.(w)``` following command to get the values of  the second stage variables ```w```, it says  ```UndefVarError: w not defined```. Could you please let me know if I am missing something here? Thanks!

**Comment by martinbiel** [comment]
You need to first access the recourse decision using for example `w = sp[2,:w]` (2 for stage 2 and :w for the relevant variable). Because the value is scenario dependent, you need to specify the scenario: `JuMP.value(w,1)` (for the optimal value in the first scenario). This is explained further in the [documentation](https://martinbiel.github.io/StochasticPrograms.jl/stable/manual/decisions/).

Consider [discourse](https://discourse.julialang.org/c/domain/opt/) for further usage questions as the answers will be more easily accessible for others :slightly_smiling_face:
